name = "halftonewavesapp"
compatibility_date = "2024-01-15"

[env.production]
name = "halftonewavesapp"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"

[build]
command = "npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"
